# Generated by Django 2.2.1 on 2019-07-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=10)),
                ('acc_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('type_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamiento.TypeCode')),
            ],
        ),
    ]
