# Generated by Django 2.2.1 on 2019-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alojamiento', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('localidad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('tipo_alojamiento', models.CharField(max_length=30)),
                ('cant_estrellas', models.CharField(max_length=30)),
            ],
        ),
    ]
