# Generated by Django 2.2.1 on 2019-05-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alojamiento',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='alojamiento',
            old_name='cant_estrellas',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='alojamiento',
            old_name='provincia',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='alojamiento',
            old_name='localidad',
            new_name='town',
        ),
        migrations.RenameField(
            model_name='alojamiento',
            old_name='tipo_alojamiento',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='nombre_alojamiento',
        ),
    ]
